make possible to redefinition of build.gradle.in by user
LaurentGomila/qt-android-cmake pull request #45
Opened 2021-09-13 14:15 UTC by Dushistov

fixes #40

2021-09-14 13:46 UTC, LaurentGomila requested changes
Thanks for contributing.

Can you add this to the documentation please (readme.md)?

2021-09-14 13:46 UTC, LaurentGomila commented on AddQtAndroidApk.cmake
> +          set(BUILD_GRADLE_TEMPLATE "${ARG_PACKAGE_SOURCES}/build.gradle.in")
Not correctly indented here (should be 4 spaces).

2021-09-14 14:07 UTC, Dushistov commented on AddQtAndroidApk.cmake
> +          set(BUILD_GRADLE_TEMPLATE "${ARG_PACKAGE_SOURCES}/build.gradle.in")
fixed

2021-11-30 12:02 UTC, Dushistov commented
> Can you add this to the documentation please (readme.md)?

I somehow missed your comment. I added mention of build.gradle.in into readme.

2022-05-04 20:02 UTC, kafeg commented
Could this be merged please?

2022-05-09 05:41 UTC, LaurentGomila approved these changes

2022-05-09 05:42 UTC, merged

2022-05-09 05:42 UTC, LaurentGomila commented
Sorry, I completely forgot about it.